{% set name = "meta-index" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BlankenbergLab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 40cdff712af03e782dfcbfa9ac03aaf19a005add1d8e8cbc35054bc78b78a03f

build:
  number: 0
  skip: True  # [py<37 or not linux]

requirements:
  run:
    - bc >=1.07.1
    - python
    - ncbitax2lin >=2.0.2
    - wget >=1.20.1
    - howdesbt >=2.00.02
    - kmtricks >=1.2.1

test:
  commands:
    - meta-index --version

about:
  home: https://github.com/BlankenbergLab/meta-index
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: meta-index pipeline
  description: |
    A pipeline for automatically indexing genomes and accurately 
    characterizing metagenome-assembled genomes with sequence bloom trees.

extra:
  recipe-maintainers:
    - fabio-cumbo
