{% set name = "MetaSBT" %}
{% set version = "0.1.0-alpha" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cumbof/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a4cd8ff3d0538aebee72e2932ced21986d03987309466d7d6ecd58e14a7ffa9d

build:
  number: 0
  skip: True  # [py<38 or not linux]
  entry_points:
    - metasbt=metasbt.metasbt:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - checkm-genome >=1.2.0
    - howdesbt >=2.00.02
    - kmtricks >=1.2.1
    - ncbi-genome-download >=0.3.1
    - ncbitax2lin >=2.3.2
    - ntcard >=1.2.2
    - numpy >=1.22.3
    - python
    - tqdm >=4.38.0
    - wget >=1.21.3

test:
  imports:
    - metasbt
  commands:
    - pip check
    - metasbt --version
  requires:
    - pip

about:
  home: https://github.com/cumbof/MetaSBT
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microbial genomes characterization with Sequence Bloom Trees
  description: |
   A scalable framework for automatically indexing microbial genomes and accurately 
   characterizing metagenome-assembled genomes with Sequence Bloom Trees

extra:
  recipe-maintainers:
    - cumbof
