{% set name = "meta-index" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BlankenbergLab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 40cdff712af03e782dfcbfa9ac03aaf19a005add1d8e8cbc35054bc78b78a03f

build:
  number: 0
  skip: True  # [py<38 or not linux]
  entry_points:
    - meta-index=meta-index.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - checkm-genome >=1.2.0
    - howdesbt >=2.00.02
    - kmtricks >=1.2.1
    - ncbi-genome-download >=0.3.1
    - ncbitax2lin >=2.3.2
    - ntcard >=1.2.2
    - numpy >=1.22.3
    - python
    - tqdm >=4.38.0
    - wget >=1.21.3

test:
  commands:
    - meta-index --version

about:
  home: https://github.com/cumbof/meta-index
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: meta-index pipeline
  description: |
   A pipeline for automatically indexing microbial genomes and accurately 
   characterizing metagenome-assembled genomes with sequence bloom trees

extra:
  recipe-maintainers:
    - cumbof
